name: demo day 3
on: workflow_dispatch
  # push:
  #     branches:
  #       - main
  #       - dev


jobs:
  Job_1:
    runs-on: ubuntu-20.04
    steps:
        - name: checkout repository
          uses: actions/checkout@v4
          with:
            ref: faizan
          
