name: demo day 3
on: 
  push:
      branches:
        - main
        - dev
  workflow_dispatch:

jobs:
  Job_1:
    runs-on: ubuntu-20.04
    steps:
        - name: checkout repository
          uses: actions/checkout@v4
          
